/**
 * CURRENT GLOBAL TOURNAMENT CONFIG
 *
 * Update these values each month for the new tournament:
 *   - name / subtitle: display name split across two lines in the header
 *   - description: short blurb shown under the header
 *   - cardPool: Set of card names allowed in this tournament (base variants only)
 *
 * The backend game_mode and tournament_id are set separately in:
 *   clashgpt/app/routers/api.py → CURRENT_GLOBAL_TOURNAMENT
 */

export const TOURNAMENT_CONFIG = {
  /**
   * Set to false between tournaments — the decks page will show an inactive
   * screen instead of results. The leaderboard is unaffected (always live).
   */
  enabled: false,
  /** First line of the large heading (white/foreground) */
  name: "Royal",
  /** Second line of the large heading (amber gradient) */
  subtitle: "Tournament",
  /** Short description shown in the deck-browser header */
  description: "Browse decks from this month's Royal global tournament.",
  /** Cards available in this tournament (base variants only — no evos or heroes) */
  cardPool: new Set([
    "Archer Queen",
    "Archers",
    "Arrows",
    "Baby Dragon",
    "Balloon",
    "Bandit",
    "Barbarian Barrel",
    "Barbarian Hut",
    "Barbarians",
    "Bats",
    "Battle Healer",
    "Battle Ram",
    "Berserker",
    "Bomb Tower",
    "Bomber",
    "Boss Bandit",
    "Bowler",
    "Cannon",
    "Cannon Cart",
    "Clone",
    "Dark Prince",
    "Dart Goblin",
    "Earthquake",
    "Electro Dragon",
    "Electro Giant",
    "Electro Spirit",
    "Electro Wizard",
    "Elite Barbarians",
    "Elixir Collector",
    "Elixir Golem",
    "Executioner",
    "Fire Spirit",
    "Fireball",
    "Firecracker",
    "Fisherman",
    "Flying Machine",
    "Freeze",
    "Furnace",
    "Giant",
    "Giant Skeleton",
    "Giant Snowball",
    "Goblin Barrel",
    "Goblin Cage",
    "Goblin Curse",
    "Goblin Demolisher",
    "Goblin Drill",
    "Goblin Gang",
    "Goblin Giant",
    "Goblin Hut",
    "Goblin Machine",
    "Goblins",
    "Goblinstein",
    "Golden Knight",
    "Golem",
    "Graveyard",
    "Guards",
    "Heal Spirit",
    "Hog Rider",
    "Hunter",
    "Ice Golem",
    "Ice Spirit",
    "Ice Wizard",
    "Inferno Dragon",
    "Inferno Tower",
    "Knight",
    "Lava Hound",
    "Lightning",
    "Little Prince",
    "Lumberjack",
    "Magic Archer",
    "Mega Knight",
    "Mega Minion",
    "Mighty Miner",
    "Miner",
    "Mini P.E.K.K.A",
    "Minion Horde",
    "Minions",
    "Mirror",
    "Monk",
    "Mortar",
    "Mother Witch",
    "Musketeer",
    "Night Witch",
    "P.E.K.K.A",
    "Phoenix",
    "Poison",
    "Prince",
    "Princess",
    "Rage",
    "Ram Rider",
    "Rascals",
    "Rocket",
    "Royal Delivery",
    "Royal Ghost",
    "Royal Giant",
    "Royal Hogs",
    "Royal Recruits",
    "Rune Giant",
    "Skeleton Army",
    "Skeleton Barrel",
    "Skeleton Dragons",
    "Skeleton King",
    "Skeletons",
    "Sparky",
    "Spear Goblins",
    "Spirit Empress",
    "Suspicious Bush",
    "Tesla",
    "The Log",
    "Three Musketeers",
    "Tombstone",
    "Tornado",
    "Valkyrie",
    "Vines",
    "Void",
    "Wall Breakers",
    "Witch",
    "Wizard",
    "X-Bow",
    "Zap",
    "Zappies",
  ]),
} as const;
